version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@database/forestguard
    volumes:
      - ./backend:/app
    command: sh -c "celery -A celery_app worker --loglevel=info & uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - database
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: forestguard
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

   redis:
     image: redis:alpine
     ports:
       - "6379:6379"

   ml:
     build: ./ml
     ports:
       - "5000:5000"
     volumes:
       - ./ml:/app
     command: python inference.py

volumes:
  db_data: